### ISSUE TITLE
Would like to offer domain

### ISSUE THREAD

**Issue by Nebukadneza** [jca41/rramen#29]
Hi,

love the idea — and I’d like to support your project. If you want a cooler domain, I could offer to point a A/AAAA record of `www.ram.en.it` (or maybe `recipes.ram.en.it`?) to your server. I’d keep the domain at least the next couple of years, and … if you like the name, we could go ahead ^_^.

**Comment by jca41** [comment]
Hi!

Thanks for the support, I'm glad you like the idea - I think it makes sense to give those recipes a bit more visibility and structure!

Would ramen.en.it be a possibility? Or reddit-ramen.en.it?

If not I would like to stick with the current url for now.

Asides from that you're always welcome to contribute to the project!

**Comment by Nebukadneza** [comment]
The idea with the weird `.en.it` TLD is that you have the `en` from ram**en** in the domain. So it can be spoken and has some kind of context.
If you don't like the `ram.en.it` part (which is thought was funny), no problem, I just thought I’d offer what i have anyways.

Feel free to close in that case ^_^.

Best & Thanks,
-Dario
